name: CI

on:
  pull_request_review:
    types: [submitted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.review.state == 'approved'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository to the branch associated with the PR
      - uses: actions/checkout@v3
        with:
          ref: ${{ format('refs/heads/{0}', github.event.pull_request.head.ref)}}
          fetch-depth: 0

      - name: Check if any files have changed
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            config/**/test.json

      # Runs a set of commands using the runners shell
      - name: Fail if files have changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: exit 1
